# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
import dracula.draw

config.load_autoconfig()

# Theme: Dracula
dracula.draw.blood(c, {
    'spacing': {
        'vertical': 6,
        'horizontal': 8
        }
    })

# Config:
c.confirm_quit = ['never']

c.content.autoplay = False;
c.content.blocking.enabled = True
c.content.blocking.hosts.block_subdomains = True
#c.content.cookies.accept = 'never'
#c.content.cookies.store = False
c.content.geolocation = 'ask'
c.content.blocking.adblock.lists = ['https://easylist.to/easylist/easylist.txt',
'https://easylist.to/easylist/easyprivacy.txt']
c.content.blocking.hosts.lists = ['https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts']
c.content.blocking.method = 'both'
#c.content.headers.do_not_track = True
c.content.headers.referer = 'same-domain'

c.content.hyperlink_auditing = True
#c.content.javascript.enabled = False
#c.content.xss_auditing = True
c.downloads.position = 'bottom'

c.downloads.location.suggestion = 'path'
c.downloads.position = 'bottom'

c.editor.command = ['vim', '-f', '{file}', 'c', 'normal{line}G{column0}l']
c.editor.remove_file = True

c.fileselect.folder.command = ['alacritty', '-e', 'ranger', '--choosedir={}']
c.fileselect.multiple_files.command = ['alacritty', '-e', 'ranger', '--choosefiles={}']
c.fileselect.single_file.command = ['alacritty', '-e', 'ranger', '--choosefile={}']

c.statusbar.position = 'top'
c.statusbar.widgets = ['search_match', 'url', 'tabs', 'progress']

c.tabs.background = True
c.tabs.favicons.show = 'never'

# Normal Mode
config.bind('+', 'zoom-in')
config.bind('-', 'zoom-out')
config.bind('.', 'cmd-repeat-last')


config.bind('<Alt-1>', 'tab-focus 1')
config.bind('<Alt-2>', 'tab-focus 2')
config.bind('<Alt-3>', 'tab-focus 3')
config.bind('<Alt-4>', 'tab-focus 4')
config.bind('<Alt-5>', 'tab-focus 5')
config.bind('<Alt-6>', 'tab-focus 6')
config.bind('<Alt-7>', 'tab-focus 7')
config.bind('<Alt-8>', 'tab-focus 8')
config.bind('<Alt-9>', 'tab-focus 9')

config.bind('Ctrl-r', 'reload')
config.bind('Ctrl-t', 'open -t')
config.bind('Ctrl-h', 'home')

config.bind('h', 'back')
config.bind('j', 'tab-next')
config.bind('k', 'tab-prev')
config.bind('l', 'forward')


