set number		"linenumbers from the start
set history=100		"history is 100 entries
colo iwtb_dark		

filetype plugin indent on

set encoding=utf-8
set ruler

"use pathogen for plugins

execute pathogen#infect() 
call pathogen#infect()

syntax on			"syntax highlighting from the start

set laststatus=2

"config lightline plugin (iwtb soon)

let g:lightline = {
	\ 'colorscheme': 'seoul256',
	\ }

"
"config startify plugin
"

let g:startify_custom_header = [
\ '       88          88                                         ',
\ '         88      88                                           ',
\ '       88888888888888                                         ',
\ '     8888  888888  8888       88  88 888888 888888 88  88  88 ',
\ '   8888888888888888888888     88  88 88  88 88     88 88   88 ',
\ '   88  88888888888888  88     888888 888888 88     88888      ',
\ '   88  88          88  88     88  88 88  88 888888 88  88  88 ',
\ '         8888  8888                                           ',
\ ]

let g:startify_lists = [
\ { 'type': 'files',	'header': ['    last modified:'] },
\ { 'type': 'bookmarks', 'header': ['    bookmarks:'] },
\ { 'type': 'dir',	'header': ['    files in folder '. getcwd()]},
\ ]

let g:startify_bookmarks = [ {'v': '~/.vim/vimrc'}, {'x': '~/.xmonad/xmonad.hs'}, {'b': '~/.config/xmobar/xmobarrc0'}, {'t': '~/CODE/tdr/'}]
